version: 0.2
env:
  variables:
    PROJECT_NAME: "sigo-frontend"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo Installing all requirements
      - npm install
      - echo Download awsexport.ts file
      - aws s3 cp s3://$S3_BUCKET/sigo-frontend/aws-exports.ts ./src/aws-exports.ts
      - aws s3 cp s3://$S3_BUCKET/sigo-frontend/env.production .env
  build:
    commands:
      - echo Bulding project
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'