version: "3.2"
services:
  sigo-frontend-prod:
    build:
      context: .
      dockerfile: docker/node/production/Dockerfile
    privileged: true
    ports:
      - 8010:80
    networks:
      - tcc-td-network
    volumes:
      - ./:/app

networks:
  tcc-td-network:
    external: true