version: "3.2"
services:
  sigo-frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    privileged: true
    ports:
      - 8010:3000
    networks:
      - tcc-td-network
    volumes:
      - ./:/app

networks:
  tcc-td-network:
    external: true